import { cardDefinitionSchema } from '../game/schema';

const cardArt = (fileName: string) => `${import.meta.env.BASE_URL}assets/cards/${fileName}`;

export const cardList = cardDefinitionSchema.array().parse([
  {
    id: 'soothe',
    name: '安撫',
    kind: 'coordination',
    description: '指定一名己方組員，Stress -3；可以降到負數。統籌卡仍支付通常的壓力費用。',
    art: cardArt('soothe.svg'),
    target: { kind: 'member', relation: 'ally' },
    effects: [{ kind: 'stress.change', target: 'selectedMember', amount: -3, allowNegative: true, source: '安撫' }],
    ai: { autoUse: true, priority: 10, when: 'allyStressAtLeast2' },
  },
  {
    id: 'oneOnOne',
    name: '一對一討論',
    kind: 'coordination',
    description: '指定一名己方組員與一項 Design / Text / AA，為該能力擲 3 顆骰子。',
    target: { kind: 'member', relation: 'ally', skillPicker: true },
    customHandler: 'oneOnOne',
  },
  {
    id: 'guide',
    name: '指導',
    kind: 'coordination',
    description: '指定能力為 0 或 1 的己方組員：擲 1 顆該能力骰並使目標 Stress +1；骰值 >= 5 + 目前能力值時，該能力永久 +1。本卡不支付通常的統籌卡壓力費用。',
    art: cardArt('guide.svg'),
    coordinationStressCost: 0,
    target: { kind: 'member', relation: 'ally', skillPicker: true },
    customHandler: 'guide',
  },
  {
    id: 'voice',
    name: '語音會議',
    kind: 'coordination',
    description: '三選一：全隊 Stress -1；全隊各獲得 1 顆 Design 骰；全隊各獲得 1 顆 Text 骰。',
    art: cardArt('voice.svg'),
    target: { kind: 'voiceMode' },
    customHandler: 'voice',
  },
  {
    id: 'polish',
    name: '精修',
    kind: 'coordination',
    description: '選擇一部我方作品或待分配區，重擲其中點數最低的 3 顆骰。',
    art: cardArt('polish.svg'),
    target: { kind: 'polishMode' },
    customHandler: 'polish',
  },
  {
    id: 'inspiration',
    name: '靈感爆發',
    kind: 'coordination',
    description: '我方全員本回合後續所有骰子不會擲出 1 或 2。',
    target: { kind: 'none' },
    effects: [{ kind: 'roll.forbid', target: 'allAllies', faces: [1, 2], duration: 'round' }],
  },
  {
    id: 'rush',
    name: '趕工',
    kind: 'coordination',
    description: '指定一部我方作品；Design / Text / AA 各自在空格中最多填入「目前回合數」顆值為 1 的骰。',
    art: cardArt('rush.svg'),
    target: { kind: 'work', relation: 'ally' },
    customHandler: 'rush',
  },
  {
    id: 'reconsider',
    name: '重新考慮一下……',
    kind: 'coordination',
    description: '舊版相容卡；已從 Standard deck 移除。指定作品篇幅 -2（最低 1），作品負責人 Stress +1。',
    art: cardArt('reconsider.svg'),
    target: { kind: 'work', relation: 'ally' },
    effects: [
      { kind: 'work.length', target: 'selectedWork', amount: -2, min: 1 },
      { kind: 'stress.change', target: 'selectedWorkOwner', amount: 1, source: '重新考慮一下……' },
    ],
  },
  {
    id: 'overtime',
    name: '突發加班',
    kind: 'event',
    description: '指定一名對手組員，Stress +2。',
    art: cardArt('overtime.svg'),
    target: { kind: 'member', relation: 'enemy' },
    effects: [{ kind: 'stress.change', target: 'selectedMember', amount: 2, source: '突發加班', external: true }],
    ai: { autoUse: true, priority: 20, when: 'enemyLowestHeadroom' },
  },
  {
    id: 'accident',
    name: '突發事故',
    kind: 'event',
    description: '指定一名敵方角色，神隱 1 回合。',
    target: { kind: 'member', relation: 'enemy' },
    effects: [{ kind: 'status.change', target: 'selectedMember', status: 'hidden', stacks: 1, durationRounds: 1, stacking: 'replace' }],
  },
  {
    id: 'writerBlock',
    name: '卡文',
    kind: 'event',
    description: '指定一名敵方角色；其本輪 Text 能力視為 0。',
    art: cardArt('writer-block.svg'),
    target: { kind: 'member', relation: 'enemy' },
    effects: [{ kind: 'status.change', target: 'selectedMember', status: 'text-stat-zero', stacks: 1, durationRounds: 1, stacking: 'replace' }],
  },
  {
    id: 'techFailure',
    name: '技術故障',
    kind: 'event',
    description: '指定一名敵方角色；其本輪 AA 能力視為 0。',
    target: { kind: 'member', relation: 'enemy' },
    effects: [{ kind: 'status.change', target: 'selectedMember', status: 'aa-stat-zero', stacks: 1, durationRounds: 1, stacking: 'replace' }],
  },
  {
    id: 'thoughtBlock',
    name: '思維阻滯',
    kind: 'event',
    description: '指定一名敵方角色；其本回合不會擲出 5 或 6。',
    target: { kind: 'member', relation: 'enemy' },
    effects: [{ kind: 'roll.forbid', target: 'selectedMember', faces: [5, 6], duration: 'round' }],
  },
]);
