import { characterDefinitionSchema } from '../game/schema';

const characterDefinitions = characterDefinitionSchema.array().parse([
  {
    id: 'pintbox',
    name: 'Pintbox',
    stats: { design: 2, text: 0, aa: 2 },
    maxStress: 5,
    affinities: ['謀', '情'],
    skillIds: ['pintboxReview', 'pintboxAI'],
    tags: ['leader', 'review'],
    portrait: '/assets/characters/portrait/pintbox.webp',
    compactPortrait: '/assets/characters/compact/pintbox.webp',
    sourceNotes: [
      '2026-09-03 07:24:17：Design 2、AA 2、壓力上限 5。',
      'Text 未在目前整理紀錄中明確列出；prototype 暫用 0。',
      '作品適性未在該角色卡紀錄中定案；目前 affinities 為 prototype 暫定。',
    ],
  },
  {
    id: 'mashiro',
    name: '真白',
    stats: { design: 2, text: 1, aa: 2 },
    maxStress: 5,
    affinities: [],
    skillIds: ['mashiroAffinity', 'mashiroSynthesis'],
    portrait: '/assets/characters/portrait/mashiro.webp',
    compactPortrait: '/assets/characters/compact/mashiro.webp',
    sourceNotes: [
      '2026-09-03 07:56:48：Text 1、Design 2、AA 2、壓力上限 5。',
      '討論明確指定全作品適性。',
    ],
  },
  {
    id: 'user79',
    name: '79',
    stats: { design: 2, text: 3, aa: 2 },
    maxStress: 4,
    affinities: ['燃', '謀'],
    skillIds: ['resonance79', 'virtualCircle79'],
    portrait: '/assets/characters/portrait/user79.webp',
    compactPortrait: '/assets/characters/compact/user79.webp',
    sourceNotes: [
      '2026-09-03 23:06:59：Text 3、Design 2、AA 2、壓力上限 4。',
      '作品適性目前沿用 prototype 暫定值。',
    ],
  },
  {
    id: 'narrator',
    name: '旁白',
    stats: { design: 1, text: 3, aa: 1 },
    maxStress: 5,
    affinities: ['笑'],
    skillIds: ['narratorOsaka', 'narratorLongForm'],
    portrait: '/assets/characters/portrait/narrator.webp',
    compactPortrait: '/assets/characters/compact/narrator.webp',
    sourceNotes: [
      '2026-09-03 08:00:45：Text 3、Design 1、AA 1。',
      '壓力上限未在目前整理紀錄中明確列出；prototype 暫用 5。',
      '作品適性目前為 prototype 暫定。',
    ],
  },
  {
    id: 'ginsakura',
    name: '銀櫻',
    stats: { design: 1, text: 2, aa: 3 },
    maxStress: 3,
    affinities: ['情', '燃'],
    skillIds: ['ginsakuraRise', 'ginsakuraSupport'],
    portrait: '/assets/characters/portrait/ginsakura.webp',
    compactPortrait: '/assets/characters/compact/ginsakura.webp',
    sourceNotes: [
      '2026-09-03 07:49:52：Text 2、Design 1、AA 3、壓力上限 3。',
      '作品適性目前為 prototype 暫定。',
    ],
  },
  {
    id: 'bluewind',
    name: '藍風',
    stats: { design: 1, text: 1, aa: 0 },
    maxStress: 3,
    affinities: ['情', '謀'],
    skillIds: ['bluewindDelusion'],
    portrait: '/assets/characters/portrait/bluewind.webp',
    compactPortrait: '/assets/characters/compact/bluewind.webp',
    sourceNotes: [
      '2026-09-03 19:21:48：Text 1、Design 1、壓力上限 3。',
      'AA 未在目前整理紀錄中明確列出；prototype 暫用 0。',
      '作品適性目前為 prototype 暫定。',
    ],
  },
  {
    id: 'triangle',
    name: '三角希',
    stats: { design: 1, text: 2, aa: 2 },
    maxStress: 4,
    affinities: [],
    skillIds: ['triangleRecovery', 'triangleAffinity', 'triangleCoordination'],
    tags: ['duo-card', 'triangle-creature'],
    portrait: '/assets/characters/portrait/triangle.webp',
    compactPortrait: '/assets/characters/compact/triangle.webp',
    portraitPosition: { x: 50, y: 12 },
    sourceNotes: [
      '2026-09-03 08:51:47：Text 2、Design 1、AA 2、壓力上限 4。',
      '「滾滾三角生物」目前規則：每回合一次，選擇自己以外的一個三角生物（不分敵我），自己與對方壓力各 -1；另保留全作品適性與統籌卡權限。',
      '目前此 id 代表「三角希」雙人卡，由三角赤 + 有希組成；兩人共用同一張 portrait、數值與技能。',
      '未來可另外新增三角赤與有希的獨立單人角色卡，不覆寫此雙人卡。',
    ],
  },
  {
    id: 'fengyang',
    name: '風揚',
    stats: { design: 3, text: 3, aa: 0 },
    maxStress: 2,
    affinities: ['謀', '情'],
    skillIds: ['commercialAuthor'],
    tags: ['commercial-author'],
    portrait: '/assets/characters/portrait/fengyang.webp',
    compactPortrait: '/assets/characters/compact/fengyang.webp',
    portraitPosition: { x: 50, y: 12 },
    sourceNotes: [
      '2026-09-03 07:29:20：Text 3、Design 3、壓力上限 2。',
      'AA 未在目前整理紀錄中明確列出；依 prototype 未列能力的資料慣例採 0。',
      '技能「商業作者」明確為不會擲出 3 以下，因此 runtime roll floor = 3。',
      '作品適性目前為 prototype 暫定。',
    ],
  },
  {
    id: 'happy',
    name: '高興',
    stats: { design: 3, text: 0, aa: 0 },
    maxStress: null,
    affinities: [],
    skillIds: ['happyContagion', 'happyEditor'],
    portrait: '/assets/characters/portrait/happy.webp',
    compactPortrait: '/assets/characters/compact/happy.webp',
    portraitPosition: { x: 50, y: 12 },
    sourceNotes: [
      '原始角色卡明確列出 Design 3、壓力上限 ∞。',
      'Text / AA 未在角色卡中列出；依目前 prototype 對未列能力的資料慣例採 0。',
      '技能「高興」：參與的作品類型變為（怪）。',
      '第二技能採後期修正版：遊戲開始時額外取得三張統籌卡。',
    ],
  },
  {
    id: 'chaos',
    name: '卡奧斯',
    stats: { design: 3, text: 3, aa: 3 },
    maxStress: null,
    affinities: [],
    skillIds: ['chaosSteadyRoll', 'chaosVitality'],
    tags: ['boss', 'not-standard-playable', 'no-stress'],
    portrait: '/assets/characters/portrait/chaos.webp',
    compactPortrait: '/assets/characters/compact/chaos.webp',
    portraitPosition: { x: 50, y: 12 },
    resource: { name: '體力', max: 5, initial: 5 },
    sourceNotes: [
      '2026-09-05 11:30:40：Text / Design / AA 全 3。',
      '體力 5，沒有壓力條；每回合體力 -1。',
      '不會擲出 3 以下；Pintbox 表示可按 Boss 設計。',
      'runtime 以角色 resource 保存體力，roundEnd -1；no-stress 使所有 Stress 變化無效。',
      '仍標記 not-standard-playable，不加入一般 3v3 隨機池。',
    ],
  },
  {
    id: 'meteor',
    name: '流星',
    stats: { design: 0, text: 1, aa: 2 },
    maxStress: 4,
    affinities: [],
    skillIds: ['meteorTrack', 'meteorCoordination'],
    tags: ['vice-leader'],
    portrait: '/assets/characters/portrait/meteor.webp',
    compactPortrait: '/assets/characters/compact/meteor.webp',
    portraitPosition: { x: 50, y: 12 },
    sourceNotes: [
      '2026-09-03 07:20:07：PintBox 明確設計「流星」卡：Text 1、AA 2；技能「軌」在（燃）作品時可額外擲 2 顆骰取高；「副組長聖體」可使用統籌卡但自身壓力 +1。',
      '2026-09-03 07:32:45：PintBox 後續將流星壓力上限修正為約 4，因此採 4。',
      'Design 未在卡面訊息中列出；依目前 prototype 對未列能力的慣例採 0。',
      '「軌」runtime：每回合一次，自己的作品為（燃）時擲兩次 Text 判定並保留較高者作為 1 顆額外 Text 骰。',
      '「副組長聖體」runtime：隊伍使用統籌卡時，具此權限的流星代替隊長承擔 +1 外部壓力。',
      'dataset(1).zip 中 METEOR 共 1637 則訊息；其短促直接、對資訊節奏敏感的發言用於 visual brief，但不改寫 PintBox 已定義的卡面數值。',
    ],
  },
  {
    id: 'yashiro',
    name: '八代',
    stats: { design: 1, text: 1, aa: 3 },
    maxStress: 5,
    affinities: [],
    skillIds: ['yashiroQuickLearner', 'yashiroDeepResearch'],
    tags: ['triangle-creature'],
    portrait: '/assets/characters/portrait/yashiro.webp',
    compactPortrait: '/assets/characters/compact/yashiro.webp',
    portraitPosition: { x: 50, y: 12 },
    sourceNotes: [
      '2026-09-02 07:05:59：PintBox 卡面片段明確列 AA 3、壓力上限 5，以及「可愛又好學：回合開始時壓力最大的組員壓力 -1」。',
      '2026-09-03 07:57:17：PintBox 再次描述八代每回合減全組壓力是隊伍撐到最後的重要來源。',
      'Design / Text 未在卡面片段列出；依 PintBox 2026-09-05 12:04:02 定義的標準白板採 1 / 1。',
      '2026-09-04 03:35–03:37：PintBox 明確表示八代找資料的深度遠超預期，甚至追到紀念網站；本人也表示自己很認真又開心地參加組活。',
      '「查到比預期更深」為 source-driven prototype skill：每回合一次額外取得 1 顆最低為 3 的 Text 骰，表現深入查證而非單純提高常駐能力。',
      'dataset(1).zip 中「三角便當盒的八代」共 1170 則訊息。',
    ],
  },
  {
    id: 'lemon',
    name: '檸檬',
    stats: { design: 1, text: 1, aa: 1 },
    maxStress: 5,
    affinities: [],
    skillIds: ['lemonStrictLeader'],
    tags: ['leader'],
    portrait: '/assets/characters/portrait/lemon.webp',
    compactPortrait: '/assets/characters/compact/lemon.webp',
    portraitPosition: { x: 50, y: 12 },
    sourceNotes: [
      '2026-09-05 05:50:27：PintBox 將檸檬與風揚並列為「比較嚴格的組長」。',
      '2026-09-02 07:35–07:38：檸檬評論作品時反覆強調整體脈絡、連貫性、即時溝通，以及問題出現時應先做預案。',
      '基礎數值採 PintBox 2026-09-05 12:04:02 所述標準白板：Design / Text / AA 各 1、壓力上限 5，屬 Prototype assumption。',
      '「嚴格的組長」runtime 為 source-driven prototype：每回合第一次有我方角色工作骰出 1 或 2 時，重擲最低的一顆，表現提前介入與預案修正。',
      'dataset(1).zip 中「【自掛東南枝】檸檬」共 2425 則訊息；在新增角色中發言量最高。',
    ],
  },
  {
    id: 'emotion',
    name: '情緒',
    stats: { design: 1, text: 1, aa: 1 },
    maxStress: 5,
    affinities: [],
    skillIds: ['emotionCraftAwareness'],
    portrait: '/assets/characters/portrait/emotion.webp',
    compactPortrait: '/assets/characters/compact/emotion.webp',
    portraitPosition: { x: 50, y: 12 },
    sourceNotes: [
      '2026-09-03 07:12:37：PintBox 明確評價情緒屬於「有意識」能想到簡單改善 AA 效果的人，並表示做 AA 最重要的是意識、其次才是技術。',
      '本人發言同時具有強烈的語氣與氣氛敏感度，例如對作品效果直接判斷「但崩」，以及提醒不要在悲傷情境放笑面 emoji。',
      '基礎數值採 PintBox 2026-09-05 12:04:02 所述標準白板：Design / Text / AA 各 1、壓力上限 5，屬 Prototype assumption。',
      '「改善效果的意識」runtime 為 source-driven prototype：每回合一次，把自己尚未分配的一顆 AA 骰 +1，代表有意識地做小幅但有效的呈現修正。',
      'dataset(1).zip 中「〖ヰ/情緒〗何ヰ味穹蘆【消滅旁白】」共 1600 則訊息。',
    ],
  },
  {
    id: 'avocado',
    name: '酪梨',
    stats: { design: 1, text: 1, aa: 1 },
    maxStress: 5,
    affinities: [],
    skillIds: ['avocadoManual'],
    tags: ['technical', 'triangle-creature'],
    portrait: '/assets/characters/portrait/avocado.webp',
    compactPortrait: '/assets/characters/compact/avocado.webp',
    portraitPosition: { x: 50, y: 12 },
    sourceNotes: [
      '2026-09-05 05:12:21：PintBox 明確提到「酪梨不是有發使用說明嗎，跟著用應該就行」。',
      '2026-09-05 05:17:35：PintBox 表示若自己當組長，會先把酪梨的 code 實際跑一次，理解其能力邊界。',
      '2026-09-03 06:10:34：本人整理自己的「使用說明書」，明確劃分技術人員職責、會議、留存與可追溯流程。',
      '2026-09-05 05:20–05:26：本人反覆談到修改困難、AI 把修改洗回去、功能雖能做但會衍生很多 bug，呈現強烈的 implementation-boundary 意識。',
      '基礎數值採 PintBox 2026-09-05 12:04:02 所述標準白板：Design / Text / AA 各 1、壓力上限 5，屬 Prototype assumption。',
      '「使用說明」runtime：遊戲開始時額外取得一張「指導」，代表把技術能力與限制整理成其他人可以直接使用的說明。',
      'dataset(1).zip 中「【G組有獎徵稿中】酪梨控【】」共 1101 則訊息。',
    ],
  },
  {
    id: 'kitsu',
    name: 'キツ',
    stats: { design: 1, text: 1, aa: 1 },
    maxStress: 5,
    affinities: [],
    skillIds: ['kitsuReplayThirty'],
    tags: ['qa', 'regression'],
    portrait: '/assets/characters/portrait/kitsu.webp',
    compactPortrait: '/assets/characters/compact/kitsu.webp',
    portraitPosition: { x: 50, y: 12 },
    sourceNotes: [
      '2026-09-02 10:20:29：本人明確表示「做完當天我大概重播了30次」。',
      '2026-09-02 11:08:24：本人抓到「緞刀的背景又回原樣了」，屬於明確 regression observation。',
      '2026-09-02 11:12:15：本人指出兩段內容其實有關聯，顯示除了表面錯誤外也會檢查前後脈絡。',
      '基礎數值採 PintBox 2026-09-05 12:04:02 所述標準白板：Design / Text / AA 各 1、壓力上限 5，屬 Prototype assumption。',
      '「重播三十次」runtime：每回合第一次自己工作骰出 1 時，自動重擲最低的一顆；用反覆驗證抓掉最明顯 regression。',
      'dataset(1).zip 中「キツ」共 1086 則訊息。',
    ],
  },
  {
    id: 'grimm',
    name: '格林',
    stats: { design: 1, text: 2, aa: 2 },
    maxStress: 3,
    affinities: ['情', '燃'],
    skillIds: ['grimmBurningFrame'],
    tags: ['leader', 'visual-storyteller'],
    portrait: '/assets/characters/portrait/grimm.webp',
    compactPortrait: '/assets/characters/compact/grimm.webp',
    portraitPosition: { x: 50, y: 12 },
    sourceNotes: [
      '2026-09-01 23:40:56：PintBox 將格林描述為「長板很突出但有召喚代價」的類型。',
      '2026-09-05 11:09:30–11:12:42：PintBox 將格林與 79 並列為燃燒自己產出好作品的類型，並明確設計格林版為「自身 +1 壓力，給一顆 AA 骰 +2 數值」。',
      '對話反覆提到漫畫分鏡、閉關製作、童話作家與規劃較弱；據此 Prototype 採 Design 1 / Text 2 / AA 2、Stress 3、適性（情／燃）。',
      '外觀未由 source 明確定義；runtime art 的人物外觀屬 Prototype art direction，僅以分鏡、童話與高投入畫面創作作為視覺依據。',
    ],
  },
  {
    id: 'pigeon',
    name: '鴿子的化身',
    stats: { design: 1, text: 2, aa: 1 },
    maxStress: 3,
    affinities: ['謀', '情'],
    skillIds: ['pigeonReaderPerspective'],
    tags: ['editorial', 'reader-perspective'],
    portrait: '/assets/characters/portrait/pigeon.webp',
    compactPortrait: '/assets/characters/compact/pigeon.webp',
    portraitPosition: { x: 50, y: 12 },
    sourceNotes: [
      '2026-09-05 11:22:13：PintBox 直接回覆鴿子的卡面基礎為 Text 2 / Design 1 / AA 1 / Stress 4。',
      '2026-09-05 11:25:52–11:29:17：PintBox 再確認「鴿子只有壓力 3 嗎」並暫定 3，因此以後續值 Stress 3 為準。',
      'PintBox 同時明確表示技能觀測資料不足；「讀者視角」因此標為 source-driven Prototype skill，不冒充原始 PintBox 技能。',
      '本人多次討論資訊優先度、讀者實際讀到什麼、減少文字量與節奏；Prototype 適性採（謀／情）。',
    ],
  },
  {
    id: 'tanxi',
    name: '嘆息',
    stats: { design: 1, text: 1, aa: 1 },
    maxStress: 3,
    affinities: ['情'],
    skillIds: ['tanxiHardPush', 'tanxiHardToCoordinate'],
    tags: ['solo-creator', 'stress-driven'],
    portrait: '/assets/characters/portrait/tanxi.webp',
    compactPortrait: '/assets/characters/compact/tanxi.webp',
    portraitPosition: { x: 50, y: 12 },
    sourceNotes: [
      '2026-09-05 11:30:10：本人主動向 PintBox 詢問角色卡；PintBox 回覆目前只能給較低能力值。',
      '2026-09-05 11:32:10：PintBox 明確給出 Design 1、壓力上限 3，並表示目前能想到的技能偏負面。',
      'Text / AA 未在 PintBox 卡面討論中明確定義；依標準白板採 1 / 1，屬 Prototype assumption。',
      '本人表示「幾乎都是硬憋的作品分高一點，比較用心的就比較低」，因此「硬憋」設計為 source-driven Prototype skill。',
      'PintBox 後續把嘆息與鬼影並列為較難和其他人配合的類型；「難以配合」以每回合一次的負面壓力觸發表現。',
    ],
  },
  {
    id: 'ghostshadow',
    name: '鬼影',
    stats: { design: 0, text: 2, aa: 1 },
    maxStress: 2,
    affinities: ['笑'],
    skillIds: ['ghostLoosePunchlines', 'ghostHardToCoordinate'],
    tags: ['gag-writer', 'solo-creator'],
    portrait: '/assets/characters/portrait/ghostshadow.webp',
    compactPortrait: '/assets/characters/compact/ghostshadow.webp',
    portraitPosition: { x: 50, y: 12 },
    sourceNotes: [
      '2026-09-05 11:42:37：PintBox 直接評估鬼影為「布置下任務後鑽回去掏出東西」的類型，明確給出 Text 2、壓力上限 2。',
      '同一段 PintBox 將鬼影與嘆息並列為較難和其他人配合、會帶負面技能的類型。',
      '2026-09-05 11:44:20–11:44:57：PintBox 表示鬼影主要在寫鬆散段子，而且很好笑；Design 以去年組活觀感而言「不太像正常東西」。',
      'Design 0 為依上述 Design 評語與專案對能力 0 的 prototype 慣例做出的 Prototype assumption；AA 未明確列出，採標準白板 1。',
      '作品適性（笑）與技能「鬆散段子」為 source-driven Prototype design；不宣稱為 PintBox 原始卡面定案。',
    ],
  },
  {
    id: 'patrick',
    name: '派大星',
    stats: { design: 2, text: 2, aa: 1 },
    maxStress: 4,
    affinities: ['謀'],
    skillIds: ['patrickConsistencyCheck'],
    tags: ['systems-thinker', 'review', 'graph-selected'],
    portrait: '/assets/characters/portrait/patrick.webp',
    compactPortrait: '/assets/characters/compact/patrick.webp',
    portraitPosition: { x: 50, y: 12 },
    sourceNotes: [
      '本角色不是 PintBox 已有卡面設計；依使用者指定 fallback 規則，從 dataset(1).zip 的發言 reply graph 選出。',
      '派大星（.dapie）reply graph degree = 524，為排除既有角色與前四名 PintBox 直接設計候選後，互動度最高的明確未實裝使用者。',
      '本人發言反覆涉及資訊揭露、段落分配、前後一致性、整合與排程，並提出以資料庫權重檢索對話關鍵字；因此定位為系統／結構檢查型。',
      'Design 2 / Text 2 / AA 1 / Stress 4、適性（謀）與技能均為 source-driven Prototype design，不宣稱為 PintBox 原始設定。',
    ],
  },

]);

function withBaseUrl(assetPath: string | undefined): string | undefined {
  if (!assetPath) return undefined;
  const relativePath = assetPath.startsWith('/') ? assetPath.slice(1) : assetPath;
  return `${import.meta.env.BASE_URL}${relativePath}`;
}

export const characterList = characterDefinitions.map((character) => ({
  ...character,
  portrait: withBaseUrl(character.portrait),
  compactPortrait: character.compactPortrait ? withBaseUrl(character.compactPortrait) : undefined,
}));
