import { characterDefinitionSchema } from '../game/schema';

export const characterList = characterDefinitionSchema.array().parse([
  {
    id: 'pintbox',
    name: 'Pintbox',
    stats: { design: 2, text: 0, aa: 2 },
    maxStress: 5,
    affinities: ['謀', '情'],
    skillIds: ['pintboxReview', 'pintboxAI'],
    tags: ['leader', 'review'],
    portrait: '/assets/characters/pintbox.webp',
  },
  {
    id: 'mashiro',
    name: '真白',
    stats: { design: 2, text: 1, aa: 2 },
    maxStress: 5,
    affinities: [],
    skillIds: ['mashiroAffinity', 'mashiroSynthesis'],
    portrait: '/assets/characters/mashiro.webp',
  },
  {
    id: 'user79',
    name: '79',
    stats: { design: 2, text: 3, aa: 2 },
    maxStress: 4,
    affinities: ['燃', '謀'],
    skillIds: ['resonance79', 'virtualCircle79'],
    portrait: '/assets/characters/user79.webp',
  },
  {
    id: 'narrator',
    name: '旁白',
    stats: { design: 1, text: 3, aa: 1 },
    maxStress: 5,
    affinities: ['笑'],
    skillIds: ['narratorOsaka', 'narratorLongForm'],
    portrait: '/assets/characters/narrator.webp',
  },
  {
    id: 'ginsakura',
    name: '銀櫻',
    stats: { design: 1, text: 2, aa: 3 },
    maxStress: 3,
    affinities: ['情', '燃'],
    skillIds: ['ginsakuraRise', 'ginsakuraSupport'],
    portrait: '/assets/characters/ginsakura.webp',
  },
  {
    id: 'bluewind',
    name: '藍風',
    stats: { design: 1, text: 1, aa: 0 },
    maxStress: 3,
    affinities: ['情', '謀'],
    skillIds: ['bluewindDelusion'],
    portrait: '/assets/characters/bluewind.webp',
  },
  {
    id: 'triangle',
    name: '三角希',
    stats: { design: 1, text: 2, aa: 2 },
    maxStress: 4,
    affinities: [],
    skillIds: ['triangleRecovery', 'triangleAffinity'],
  },
  {
    id: 'fengyang',
    name: '風揚',
    stats: { design: 3, text: 3, aa: 0 },
    maxStress: 2,
    affinities: ['謀', '情'],
    skillIds: ['commercialAuthor'],
  },
]);
